# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: uaerealstatehub
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
    profiles:
      - ''
      - prod
